### ISSUE TITLE
预训练模型和NYUD数据集的一点小问题

### ISSUE THREAD

**Issue by 2916850681** [yun-liu/RCF-PyTorch#2]
您好，问题有点多，打扰了
1.请问一下这个预训练模型与pytorch官方预训练模型是否相同，可以替换吗？
2.BSDS和NYUD都使用同样的预训练模型吗？
3.NYUD-HHA数据集与NYUD-RGB相比，除了均值需要改以外，还有哪些不一样的地方？

初窥深度学习门道，问题有点低级，若有冒犯，还请海涵。

**Comment by yun-liu** [comment]
您好。

> 1. 请问一下这个预训练模型与pytorch官方预训练模型是否相同，可以替换吗？

不一样，不能替换。我提供的预训练模型是Caffe的模型，和PyTorch的不一样。替换后的效果如何，没有测试。这个代码是按照Caffe版本的代码来实现的。

> 2. BSDS和NYUD都使用同样的预训练模型吗？

是的。这点也和Caffe版一样。

> 3. NYUD-HHA数据集与NYUD-RGB相比，除了均值需要改以外，还有哪些不一样的地方？

只有均值不一样。可以参考[论文](https://yun-liu.github.io/papers/(TPAMI'2019)Richer%20Convolutional%20Features%20for%20Edge%20Detection.pdf)4.2节的描述或者[Caffe代码](https://github.com/yun-liu/RCF)的实现。

**Comment by 2916850681** [comment]
好的，非常感谢



---原始邮件---
发件人: "Yun ***@***.***&gt;
发送时间: 2022年1月9日(周日) 晚上8:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yun-liu/RCF-PyTorch] 预训练模型和NYUD数据集的一点小问题 (Issue #2)




 
您好。
   
请问一下这个预训练模型与pytorch官方预训练模型是否相同，可以替换吗？ 
  
不一样，不能替换。我提供的预训练模型是Caffe的模型，和PyTorch的不一样。替换后的效果如何，没有测试。这个代码是按照Caffe版本的代码来实现的。
   
BSDS和NYUD都使用同样的预训练模型吗？ 
  
是的。这点也和Caffe版一样。
   
NYUD-HHA数据集与NYUD-RGB相比，除了均值需要改以外，还有哪些不一样的地方？ 
  
只有均值不一样。可以参考论文4.2节的描述或者Caffe代码的实现。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yun-liu** [comment]
ImageNet预训练模型的百度网盘：
链接：https://pan.baidu.com/s/1vfntX-cTKnk58atNW5T1lA?pwd=g5af 
提取码：g5af

BSDS500 +PASCAL的edge模型：
链接：https://pan.baidu.com/s/1Tpf_-dIxHmKwH5IeClt0Ng?pwd=03ad 
提取码：03ad

**Comment by yun-liu** [comment]
我在Github上回复您了，请移步阅读。

2916850681 ***@***.***> 于2022年1月8日周六 11:58写道：

**Comment by 2916850681** [comment]
> ImageNet预训练模型的百度网盘： 链接：https://pan.baidu.com/s/1vfntX-cTKnk58atNW5T1lA?pwd=g5af 提取码：g5af
> 
> BSDS500 +PASCAL的edge模型： 链接：https://pan.baidu.com/s/1Tpf_-dIxHmKwH5IeClt0Ng?pwd=03ad 提取码：03ad
