### ISSUE TITLE
复现在NYUD的结果与论文中相差较大

### ISSUE THREAD

**Issue by 2916850681** [yun-liu/RCF-PyTorch#3]
您好，再次打扰，实在抱歉。在NYUD结果复现过程中发现了几个小问题，希望能得到您的指教
1.使用您提供的数据增强代码（https://github.com/yun-liu/RCF/issues/124#issuecomment-792220875）
发现非90°倍数的旋转会产生0~255之间的中间结果，但是您在其他回答里（https://github.com/yun-liu/RCF/issues/65#issuecomment-439662243）
说是二值结果，请问是我的操作有问题吗？在实际操作中把他们用127.5二值化还是像BSDS500一样有个忽略范围（不求损失）
下图是对NYUDv2/train/GT/112.5_0/img_6116.png各像素强度的统计结果，出现非 0和255的值：
![image](https://user-images.githubusercontent.com/44263056/149708741-0f426b07-be75-4468-89b3-2074724ea828.png)
2.在实验中发现随机初始化的随机化种子对结果精度有非常大的影响，您对这一块有过研究吗？
3.我得到最高的NYUD-RGB的ODS、OIS为0.735415 0.753693  与您在论文里得到的精度（0.743 0.757）相比，可以认为是在允许的误差范围内吗

期待您的回复

**Comment by yun-liu** [comment]
1. 你检查一下是不是你的代码或者数据有问题，旋转应该不会改变像素的值吧？当时用Caffe做实验的时候，默认就是BSDS500的处理方式，我没注意
2. 我跑的实验，发现随机化种子对结果没啥影响，我跑了很多次，结果都一样
3. 论文里的结果是用Caffe跑的，这个repo是一个PyTorch实现。我没测试PyTorch实现在NYUD上的结果。ODS差0.8%还是稍微有点多的，你看看loss 里的lamda，NYUD用的好像是1.2，BSDS500是1.1

**Comment by 2916850681** [comment]
这么低级的问题实在不该打扰您，但是现在NYUD数据集的训练代码几乎找不到参考，很多细节自己实在想不出来
lamda已经改成1.2了，NMS的参数也按照您在其他回答里的改过了。自己捣鼓了两个月，实在是找不到原因了 [流泪][流泪]
PAMI版本增强过后的NYUD数据集方便分享一下吗？
NYUD中怎么将label（0-255）归一化到0、1的？直接除以255吗？

**Comment by 2916850681** [comment]
> NYUD的label，处理方式跟BSDS一样 学习率，NYUD跟BSDS的是一样的
> 
> 您可以先试试用我release的那个NYUD数据集，看能不能复现出CVPR论文里的那个结果

果然，cvpr的也复现不了，NYUD-RGB比您的结果低2%，看来不是旋转带来的不利影响
我将数据集从BSDS改到NYUD做的改动有：
1.数据加载：直接将label中非0值设为1（其实这个地方可以不改，在cvpr版本中只有0，1两个值，所以bsds的处理方式结果一样）
2.重新计算数据集的均值（BGR）：92.31828, 97.20341,  116.19011
3.将lamda设为1.2
4.NMS参数按照您Caffa版本设为 E=edgesNmsMex(E,O,4,5,1.01,8);
5.distance tolerance 设为0.011

麻烦您看一下还有需要改动的地方吗？我的设置是不是有什么问题？

**Comment by yun-liu** [comment]
其他的好像没啥问题，就图像的均值不对，请用这个脚本提供的均值：https://github.com/yun-liu/RCF/blob/master/examples/rcf/RCF-singlescale-NYUD.ipynb
