### ISSUE TITLE
iter_size

### ISSUE THREAD

**Issue by Scott-che** [yun-liu/RCF-PyTorch#6]
![5](https://user-images.githubusercontent.com/67545227/197125505-34e40bc6-ed9d-4e15-8c88-2abd4c6aa16f.PNG)
你好，想詢問為何這邊的iter_size設置為10，及loss為什麼要除上iter_size

**Comment by yun-liu** [comment]
iter_size的作用类似 batch size

**Comment by Scott-che** [comment]
想請問這邊iter_size設置為10，是根據什麼作為基準而去設置的

**Comment by yun-liu** [comment]
大家都这么设
