### ISSUE TITLE
运行test时会出现cuda显存溢出（8G独显），请问如何解决啊

### ISSUE THREAD

**Issue by Wuoo25** [yun-liu/RCF-PyTorch#9]

**Comment by yun-liu** [comment]
out of memory? 你图像多大？

**Comment by Wuoo25** [comment]
> 错误信息是什么？out of memory? 你图像多大？
是的，显示cuda显存溢出，图像是640x512，后面在远程服务器上运行正常了

**Comment by yun-liu** [comment]
那就好。感觉640x512的图像也不大，不清楚为什么。总之能运行就好
